### ISSUE TITLE
Unable to read parameters

### ISSUE THREAD

**Issue by mdantonio** [pdonorio/rest-mock#9]
Rest mock is unable to read parameters when they are passed as call payload from AngularJS. No problem when they are encoded via url.

Not working:

RestAPI.all('/api/mylogin').post({email: "blabla", password:"blabla"})

Working: 

RestAPI.all('/api/mylogin?email=blabla&password=blabla').post()

Via CURL it works with both:

curl -X POST host/api/mylogin --data "email=blabla&password=blabla"

and

curl -X POST host/api/mylogin?email=blabla&password=blabla

**Comment by pdonorio** [comment]
The fact that curl works on both gives me some suspect about the rest
angular behavior. Can you please check @mdantonio that it didn't happened
to other angular boys? Are you testing the latest rest angular version?

**Comment by mdantonio** [comment]
Several test done, without any success

Made some search on google, without any success

I tried to put prints in the flask restful library, to try to understand what is received, without any success

I just found this, but i'm not able to understand if it can be helpful

http://stackoverflow.com/questions/19384526/how-to-parse-the-post-argument-to-a-rest-service

**Comment by pdonorio** [comment]
The link is about multiple parameters inside the url so it's not our case.

Can you paste a quick angular snippet to let me reproduce the issue?

**Comment by pdonorio** [comment]
Ok, i also need to see how you implemented your endpoint `/mylogin`.
Which is also written in flask front-end, not on our back end REST API, right?

Then i am going to:
1. Check if https://github.com/pdonorio/angulask/issues/18#issuecomment-161892855 works on /mylogin
2. Test the json data as input and output

**Comment by mdantonio** [comment]
```
credentials = {"email": "blabla", "password": "blabla}

this.login = function (credentials) {
    var url = RestAPI.all('/login');

    return url.post(credentials) 
      .then(function (data) {
          status = data.meta.code;

          if (status == 200) {

                  token = data.response.user.authentication_token;
                  id = data.response.user.id;

                  return {"status": status, "id":id, "username":credentials.email, "token":token};

          } else if (status == 400) {

                  //BEWARE!! Only the first error (with priority to email errors) will be returned!
                  emailError = data.response.errors.email;
                  pwdError = data.response.errors.password;

                  if (typeof emailError !== 'undefined') return {"status": status, "type": email, "error": emailError[0]}; //[0] -> only the first error!!
                  if (typeof pwdError !== 'undefined') return {"status": status, "password": email, "error": pwdError[0]};
                  return {"status": status, "type":"unknown", "error":"Unknown error", "extra": data.response.errors};

          } else {
                  return {"status": status, "type":"status", "error":"Unknown status", "extra": status};

          }

          return data;
      });

  };
```
